general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando que realmente tranca a sessão
    before_sleep_cmd = loginctl lock-session    # Garante o lock ANTES do PC suspender/fechar a tampa
    after_sleep_cmd = hyprctl dispatch dpms on  # Garante que a tela acende ao voltar do suspend
}

# 1. AVISO (8 minutos / 480 segundos)
# Diminui o brilho da tela para avisar que vai bloquear
listener {
    timeout = 240
    on-timeout = brightnessctl set 10%
    on-resume = brightnessctl set 100%
}

# 2. LOCK E DESLIGAR A TELA (10 minutos / 600 segundos)
# Tranca o PC e desliga os monitores completamente
listener {
    timeout = 600
    on-timeout = loginctl lock-session && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
